### ISSUE TITLE
No permissions to clone subdirectory

### ISSUE THREAD

**Issue by thewithz** [Pitt-CSC/PittAPIWebWrapper#14]
https://hastebin.com/yiwojakoke.pl

Says I can't clone the sub module because I don't have correct access rights. Can I just clone the PittAPI repo separately into the `apiwrapper` directory, or is there a specific version that I need?

**Comment by dzheng256** [comment]
just invited you to the Pitt-CSC organization. does it work now?

**Comment by timparenti** [comment]
You need to [set up SSH keys with Github](https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/).

You're cloning the main repo over the HTTPS protocol, which requires entering your Github username and password, but the submodules are being pulled over the SSH protocol, which requires SSH keys.

**Comment by thewithz** [comment]
hmmm, good to know for the future, thank you. I just cloned the PittAPI separately and it worked perfectly fine.
